name: local_file_screenshot_processor
description: Custom processor for screenshots taken with the Device Preview utility
version: 0.0.1
homepage: https://www.thkp.co
repository: https://github.com/AlabasterAxe/local_file_screenshot_processor

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter
